- id: '1543330438173'
  alias: Christmas Lights on at Sunset
  trigger:
  - event: sunset
    platform: sun
  action:
  - entity_id: group.christmas_lights
    service: homeassistant.turn_on
  - data:
      title: Christmas lights
      message: The lights have been turned on
    service: notify.dactylmanor_email_sender
- id: '1543332193368'
  alias: Christmas Lights off at 10:30pm
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - entity_id: group.christmas_lights
    service: homeassistant.turn_off
  - data:
      title: Christmas lights
      message: The lights have been turned off
    service: notify.dactylmanor_email_sender
- id: '1543538013967'
  alias: Shore Leave SSL
  trigger:
  - at: '17:00'
    platform: time
  condition:
  - below: '30'
    condition: numeric_state
    entity_id: sensor.shoreleave_tls_expiry
  action:
  - data:
      message: The certifcate expires in {{ states.sensor.shoreleave_tls_expiry.state
        }} days
      title: '[alert] Shore Leave TLS certificate'
    service: notify.dactylmanor_email_sender
- id: '1543629677014'
  alias: Home
  trigger:
  - entity_id: device_tracker.blair_pixel2
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data:
      message: I be home
      title: Home
    service: notify.dactylmanor_email_sender
