homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 428
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

  
# Load external configuration.
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
notify: !include notifications.yaml
zone: !include zones.yaml

  
# Enables the frontend
frontend:

# Enables configuration UI
config:

# Auto-detect iOS devices.
ios:

http:
  api_password: !secret http_password
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


sensor:
  # Weather prediction
  - platform: yr

  # Plex monitor
  #- platform: plex
  #  token: ZtsrXgzNsBb3USff4UeU

  # Shore Leave SSL Certificate
  - platform: cert_expiry
    host: www.shore-leave.com
    name: shoreleave_tls_expiry
  
# Text to speech
tts:
  - platform: google

# Disable Home Assistant Cloud service.
#cloud:


# Radio Thermostat
climate:
  - platform: radiotherm
    host: !secret thermostat_host

# Dark Sky
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    units: us
    name: Dark Sky

# Smart switches
switch:
  - platform: tplink
    host: plug1
    name: "Plug 1"
  - platform: tplink
    host: plug2
    name: "Plug 2"
  - platform: tplink
    host: plug3
    name: "Plug 3"
  - platform: tplink
    host: plug4
    name: "Plug 4"

owntracks:
  max_gps_accuracy: 100

device_tracker:
  - platform: tile
    username: !secret dactylmanor_org_email
    password: !secret tile_password
    monitored_variables: [TILE]
